#ifdef TRAINERS_WITH_EVS
/*
trainers_with_evs_table.h
	defining the EV/IV/ability/ball type to be assigned to trainer pokemon
*/

const struct TrainersWithEvs gTrainersWithEvsSpreads[] =
{
	[0] = {0}, //Empty Spread
	[1] = {
		.nature = NATURE_JOLLY,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
	},
	[2] = {
		.nature = NATURE_TIMID,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
	},
	[3] = {
		.nature = NATURE_ADAMANT,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
	},
	[4] = {
		.nature = NATURE_MODEST,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
	},
	[5] = {
		.nature = NATURE_IMPISH,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
	},
	[6] = {
		.nature = NATURE_BOLD,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
	},
	[7] = {
		.nature = NATURE_CAREFUL,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
	},
	[8] = {
		.nature = NATURE_CALM,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
	},
	[9] = {
		.nature = NATURE_NAIVE,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
	},
	[10] = {
		.nature = NATURE_HASTY,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
	},
	[11] = {
		.nature = NATURE_RASH,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
	},
	[12] = {
		.nature = NATURE_LONELY,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
	},
	[13] = {
		.nature = NATURE_MILD,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
	},
	[14] = {
		.nature = NATURE_NAUGHTY,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
	},
	[15] = {
		.nature = NATURE_BRAVE,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
	},
	[16] = {
		.nature = NATURE_QUIET,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
	},
	[17] = {
		.nature = NATURE_RELAXED,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
	},
	[18] = {
		.nature = NATURE_SASSY,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
	},
	[19] = {
		.nature = NATURE_BASHFUL,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
	},


	[21] = {
	.nature = NATURE_JOLLY,
	.ivs = 31,
	.ball = TRAINER_EV_CLASS_BALL,
	.ability = Ability_2,
	},
	[22] = {
		.nature = NATURE_TIMID,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
	},
	[23] = {
		.nature = NATURE_ADAMANT,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
	},
	[24] = {
		.nature = NATURE_MODEST,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
	},
	[25] = {
		.nature = NATURE_IMPISH,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
	},
	[26] = {
		.nature = NATURE_BOLD,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
	},
	[27] = {
		.nature = NATURE_CAREFUL,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
	},
	[28] = {
		.nature = NATURE_CALM,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
	},
	[29] = {
		.nature = NATURE_NAIVE,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
	},
	[30] = {
		.nature = NATURE_HASTY,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
	},
	[31] = {
		.nature = NATURE_RASH,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
	},
	[32] = {
		.nature = NATURE_LONELY,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
	},
	[33] = {
		.nature = NATURE_MILD,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
	},
	[34] = {
		.nature = NATURE_NAUGHTY,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
	},
	[35] = {
		.nature = NATURE_BRAVE,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
	},
	[36] = {
		.nature = NATURE_QUIET,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
	},
	[37] = {
		.nature = NATURE_RELAXED,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
	},
	[38] = {
		.nature = NATURE_SASSY,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
	},
	[39] = {
		.nature = NATURE_BASHFUL,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
	},


	[41] = {
		.nature = NATURE_JOLLY,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
	},
	[42] = {
		.nature = NATURE_TIMID,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
	},
	[43] = {
		.nature = NATURE_ADAMANT,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
	},
	[44] = {
		.nature = NATURE_MODEST,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
	},
	[45] = {
		.nature = NATURE_IMPISH,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
	},
	[46] = {
		.nature = NATURE_BOLD,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
	},
	[47] = {
		.nature = NATURE_CAREFUL,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
	},
	[48] = {
		.nature = NATURE_CALM,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
	},
	[49] = {
		.nature = NATURE_NAIVE,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
	},
	[50] = {
		.nature = NATURE_HASTY,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
	},
	[51] = {
		.nature = NATURE_RASH,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
	},
	[52] = {
		.nature = NATURE_LONELY,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
	},
	[53] = {
		.nature = NATURE_MILD,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
	},
	[54] = {
		.nature = NATURE_NAUGHTY,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
	},
	[55] = {
		.nature = NATURE_BRAVE,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
	},
	[56] = {
		.nature = NATURE_QUIET,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
	},
	[57] = {
		.nature = NATURE_RELAXED,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
	},
	[58] = {
		.nature = NATURE_SASSY,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
	},
	[59] = {
		.nature = NATURE_BASHFUL,
		.ivs = 31,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
	},

};
#endif

#ifndef UNBOUND //Modify this
const u8 gBaseIVsByTrainerClass[NUM_TRAINER_CLASSES] =
{
	[CLASS_YOUNGSTER] = 31,
	[CLASS_BUG_CATCHER] = 31,
	[CLASS_LASS] = 31,
	[CLASS_SAILOR] = 31,
	[CLASS_CAMPER] = 31,
	[CLASS_PICNICKER] = 31,
	[CLASS_POKEMANIAC] = 31,
	[CLASS_SUPER_NERD] = 31,
	[CLASS_HIKER] = 31,
	[CLASS_BIKER] = 31,
	[CLASS_BURGLAR] = 31,
	[CLASS_ENGINEER] = 31,
	[CLASS_FISHERMAN] = 31,
	[CLASS_SWIMMER_M] = 31,
	[CLASS_CUE_BALL] = 31,
	[CLASS_GAMBLER] = 31,
	[CLASS_BEAUTY] = 31,
	[CLASS_SWIMMER_F] = 31,
	[CLASS_PSYCHIC] = 31,
	[CLASS_ROCKER] = 31,
	[CLASS_JUGGLER] = 31,
	[CLASS_TAMER] = 31,
	[CLASS_BIRD_KEEPER] = 31,
	[CLASS_BLACK_BELT] = 31,
	[CLASS_RIVAL] = 31,
	[CLASS_SCIENTIST] = 31,
	[CLASS_BOSS] = 31,
	[CLASS_LEADER] = 31,
	[CLASS_TEAM_ROCKET] = 31,
	[CLASS_COOLTRAINER] = 31,
	[CLASS_ELITE_4] = 31,
	[CLASS_GENTLEMAN] = 31,
	[CLASS_RIVAL_2] = 31,
	[CLASS_CHAMPION] = 31,
	[CLASS_CHANNELER] = 31,
	[CLASS_TWINS] = 31,
	[CLASS_COOL_COUPLE] = 31,
	[CLASS_YOUNG_COUPLE] = 31,
	[CLASS_CRUSH_KIN] = 31,
	[CLASS_SIS_AND_BRO] = 31,
	[CLASS_PKMN_PROF] = 31,
	[CLASS_PLAYER] = 31,
	[CLASS_CRUSH_GIRL] = 31,
	[CLASS_TUBER] = 31,
	[CLASS_PKMN_BREEDER] = 31,
	[CLASS_PKMN_RANGER] = 31,
	[CLASS_AROMA_LADY] = 31,
	[CLASS_RUIN_MANIAC] = 31,
	[CLASS_LADY] = 31,
	[CLASS_PAINTER] = 31,
};
#else //For Pokemon Unbound
const u8 gBaseIVsByTrainerClass[NUM_TRAINER_CLASSES] =
{
	[CLASS_YOUNGSTER] = 5,
	[CLASS_BUG_CATCHER] = 1,
	[CLASS_LASS] =  5,
	[CLASS_SAILOR] = 10,
	[CLASS_CAMPER] = 5,
	[CLASS_PICNICKER] =  5,
	[CLASS_CAMPING_DUO] = 5,
	[CLASS_POKEMANIAC] = 10,
	[CLASS_SUPER_NERD] = 15,
	[CLASS_HIKER] = 10,
	[CLASS_BIKER] = 10,
	[CLASS_BURGLAR] = 10,
	[CLASS_WORKER] = 10,
	[CLASS_FISHERMAN] = 10,
	[CLASS_SWIMMER_M] = 10,
	[CLASS_SWIMMER_F] = 10,
	[CLASS_TUBER] = 5,
	[CLASS_SIS_AND_BRO] = 10,
	[CLASS_ROUGHNECK] = 10,
	[CLASS_GAMBLER] = 10,
	[CLASS_BEAUTY] =  10,
	[CLASS_PSYCHIC] = 15,
	[CLASS_ROCKER] = 10,
	[CLASS_JUGGLER] = 10,
	[CLASS_TAMER] = 20,
	[CLASS_BIRD_KEEPER] = 10,
	[CLASS_BLACK_BELT] = 15,
	[CLASS_CRUSH_GIRL] = 15,
	[CLASS_CRUSH_KIN] = 15,
	[CLASS_RIVAL] = 25,
	[CLASS_RIVAL_2] = 31,
	[CLASS_SCIENTIST] = 15,
	[CLASS_GENTLEMAN] = 15,
	[CLASS_MEDIUM] = 10,
	[CLASS_TWINS] = 5,
	[CLASS_YOUNG_COUPLE] = 15,
	[CLASS_PKMN_BREEDER] = 15,
	[CLASS_PKMN_RANGER] = 20,
	[CLASS_AROMA_LADY] = 10,
	[CLASS_RUIN_MANIAC] = 10,
	[CLASS_LADY] = 20,
	[CLASS_PAINTER] = 10,
	[CLASS_IDOL] = 20,
	[CLASS_WAITER] = 10,
	[CLASS_WAITRESS] = 10,
	[CLASS_INTERVIEWER] = 10,
	[CLASS_CYCLIST] = 10,
	[CLASS_NURSE] = 15,
	[CLASS_POKE_KID] = 5,
	[CLASS_RICH_BOY] = 20,
	[CLASS_SKIIER] = 10,
	[CLASS_GUITARIST] = 10,
	[CLASS_KINDLER] = 10,
	[CLASS_SHOCKER] = 10,
	[CLASS_BUG_MANIAC] = 10,
	[CLASS_POLICEMAN] = 15,
	[CLASS_BOARDER] = 10,
	[CLASS_SCHOOL_KID] = 5,
	[CLASS_COLLECTOR] = 10,
	[CLASS_ACE_TRAINER] = 25,
	[CLASS_ACE_DUO] = 25,
	[CLASS_JOGGER] = 10,
	[CLASS_DRAGON_TAMER] = 25,
	[CLASS_NINJA_BOY] = 10,
	[CLASS_PARASOL_LADY] = 10,
	[CLASS_POKEFAN] = 10,
	[CLASS_RANCHER] = 10,
	[CLASS_EXPERT] = 25,
	[CLASS_OLD_COUPLE] = 25,
	[CLASS_MEGA_TRAINER] = 31,

	[CLASS_SHADOW] = 18,
	[CLASS_SHADOW_ADMIN] = 31,
	[CLASS_BOSS] = 31,
	[CLASS_LOR] = 18,
	[CLASS_LOR_ADMIN] = 31,
	[CLASS_LOR_LEADER] = 31,
	[CLASS_AGENT] = 31,

	[CLASS_BLACK_EMBOAR] = 18,
	[CLASS_TERROR_GRANBULL] = 18,
	[CLASS_BLACK_FERROTHORN] = 25,
	[CLASS_BLACK_FERROTHORN_BOSS] = 31,
	[CLASS_SCIENCE_SOCIETY] = 25,
	[CLASS_BLACK_HORIZON] = 25,

	[CLASS_LEADER] = 31,
	[CLASS_SINNOH_LEADER] = 31,
	[CLASS_SUCCESSOR] = 31,
	[CLASS_ELITE_4] = 31,
	[CLASS_PKMN_PROF] = 31,
	[CLASS_DEVELOPER] = 31,
	[CLASS_CHAMPION] = 31,
	[CLASS_FRONTIER_BRAIN] = 31,
	[CLASS_PKMN_TRAINER_1] = 25,
	[CLASS_PKMN_TRAINER_2] = 25,
	[CLASS_PKMN_TRAINER_3] = 25,
};
#endif
